// This file was auto-generated by Fern from our API Definition.

export interface AccessSubject {
    type?: AccessSubject.Type | undefined;
    id?: string | undefined;
    /** The strongest role they gain or lose. */
    role?: AccessSubject.Role | undefined;
    /** The scope the grant sits on, so the change can be explained. */
    via?: string | undefined;
}

export namespace AccessSubject {
    export const Type = {
        User: "user",
        Group: "group",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** The strongest role they gain or lose. */
    export const Role = {
        Reader: "reader",
        Writer: "writer",
        Owner: "owner",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
