// This file was auto-generated by Fern from our API Definition.

import type * as ContexthubApi from "../index.js";

/**
 * What a move or rename would change about who can reach the content. Bounded
 * by what your credential can already discover: subjects you cannot see are
 * not listed, and not counted either.
 */
export interface AccessChange {
    /** Someone gains access. This is the direction that is gated. */
    widens?: boolean | undefined;
    /** Someone loses access. Reported, never gated. */
    narrows?: boolean | undefined;
    gained?: ContexthubApi.AccessSubject[] | undefined;
    lost?: ContexthubApi.AccessSubject[] | undefined;
}
