// This file was auto-generated by Fern from our API Definition.

import type * as AgentlefsApi from "../index.js";

export interface ConflictErrorBody {
    error?: ConflictErrorBody.Error_ | undefined;
}

export namespace ConflictErrorBody {
    export interface Error_ {
        code?: Error_.Code | undefined;
        message?: string | undefined;
        request_id?: string | undefined;
        access_change?: AgentlefsApi.AccessChange | undefined;
        /**
         * Whether re-sending with `acknowledge_access_change: true` can
         * succeed.
         */
        acknowledgeable?: boolean | undefined;
    }

    export namespace Error_ {
        export const Code = {
            Conflict: "CONFLICT",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
