// This file was auto-generated by Fern from our API Definition.

export interface DeleteResult {
    path?: string | undefined;
    folder?: string | undefined;
    deleted?: boolean | undefined;
    commit?: (string | null) | undefined;
}
