// This file was auto-generated by Fern from our API Definition.

export interface DeleteResult {
    /** The whole path from the workspace root. */
    location?: string | undefined;
    deleted?: boolean | undefined;
    commit?: (string | null) | undefined;
}
