// This file was auto-generated by Fern from our API Definition.

export interface DocumentContent {
    /** The whole path from the workspace root. */
    location: string;
    content: string;
    /** True when the body was capped; use `next_offset` to continue. */
    truncated?: boolean | undefined;
    total_bytes?: (number | null) | undefined;
    next_offset?: (number | null) | undefined;
    /**
     * `live` means an unsaved editing session supplied this body. If
     * your pipeline requires committed content, check this: acting
     * on a draft as though it were final is a real correctness bug.
     */
    revision: DocumentContent.Revision;
}

export namespace DocumentContent {
    /**
     * `live` means an unsaved editing session supplied this body. If
     * your pipeline requires committed content, check this: acting
     * on a draft as though it were final is a real correctness bug.
     */
    export const Revision = {
        Committed: "committed",
        Live: "live",
    } as const;
    export type Revision = (typeof Revision)[keyof typeof Revision];
}
