// This file was auto-generated by Fern from our API Definition.

export interface DocumentSummary {
    path?: string | undefined;
    type?: string | undefined;
    title?: (string | null) | undefined;
    summary?: (string | null) | undefined;
    /** Discovery metadata only. Labels confer no access. */
    labels?: string[] | undefined;
    /** True for binary assets, whose bodies are not returned as text. */
    is_asset?: boolean | undefined;
    mime?: (string | null) | undefined;
    size_bytes?: (number | null) | undefined;
}
