// This file was auto-generated by Fern from our API Definition.

import type * as ContexthubApi from "../index.js";

export interface DocumentList {
    documents: ContexthubApi.DocumentSummary[];
    /**
     * Pass as `cursor` to fetch the next page. `null` means this is
     * the last page. A cursor is bound to the query that produced
     * it and to your key: reusing one with different filters is
     * rejected rather than silently reinterpreted.
     */
    next_cursor: string | null;
}
