// This file was auto-generated by Fern from our API Definition.

import type * as AgentlefsApi from "../index.js";

export interface FolderList {
    folders: AgentlefsApi.Folder[];
    next_cursor: string | null;
}
