// This file was auto-generated by Fern from our API Definition.

export interface Folder {
    /** The addressable folder id, and the same string a permission grant names. */
    id?: string | undefined;
    folder?: string | undefined;
    /** Path within the top-level folder. Empty for the folder itself. */
    path?: string | undefined;
}
