// This file was auto-generated by Fern from our API Definition.

import type * as ContexthubApi from "../index.js";

export interface FolderList {
    folders: ContexthubApi.Folder[];
    next_cursor: string | null;
}
