// This file was auto-generated by Fern from our API Definition.

export interface FolderCreated {
    /** The folder's whole path from the workspace root. */
    location?: string | undefined;
    /**
     * The folder id, which is also the scope a grant names — the same string as
     * `location`. Kept because it is what `GET /v1/folders` calls it.
     */
    id?: string | undefined;
    commit?: string | undefined;
}
