// This file was auto-generated by Fern from our API Definition.

export interface FolderCreated {
    folder?: string | undefined;
    path?: string | undefined;
    /** The folder id, which is also the scope a grant names. */
    id?: string | undefined;
    commit?: string | undefined;
}
