// This file was auto-generated by Fern from our API Definition.

import type * as AgentlefsApi from "../index.js";

export interface GrantList {
    scope_type?: string | undefined;
    scope_id?: string | undefined;
    grants?: AgentlefsApi.Grant[] | undefined;
}
