// This file was auto-generated by Fern from our API Definition.

import type * as ContexthubApi from "../index.js";

export interface GrantList {
    scope_type?: string | undefined;
    scope_id?: string | undefined;
    grants?: ContexthubApi.Grant[] | undefined;
}
