// This file was auto-generated by Fern from our API Definition.

export interface MoveResult {
    /** The whole location before the operation. */
    from?: string | undefined;
    /**
     * The whole location after it. A rename and a move report the same two
     * fields; the three folder fields that used to sit beside them said which
     * operation had happened, which `from` and `to` already show.
     */
    to?: string | undefined;
    commit?: (string | null) | undefined;
    /**
     * Every path that actually moved. A directory rename or move reports one
     * entry per document beneath it, so this is how you learn what a subtree
     * operation touched.
     */
    changed?: MoveResult.Changed.Item[] | undefined;
    /** Present and true when this was an idempotent replay. */
    replayed?: boolean | undefined;
}

export namespace MoveResult {
    export type Changed = Changed.Item[];

    export namespace Changed {
        export interface Item {
            from?: string | undefined;
            to?: string | undefined;
        }
    }
}
