// This file was auto-generated by Fern from our API Definition.

export interface MoveResult {
    /** Present on a rename. */
    folder?: string | undefined;
    /** Present on a move. */
    from_folder?: string | undefined;
    /** Present on a move. */
    to_folder?: string | undefined;
    from?: string | undefined;
    to?: string | undefined;
    commit?: (string | null) | undefined;
    /**
     * Every path that actually moved. A directory rename or move reports one
     * entry per document beneath it, so this is how you learn what a subtree
     * operation touched.
     */
    changed?: MoveResult.Changed.Item[] | undefined;
    /** Present and true when this was an idempotent replay. */
    replayed?: boolean | undefined;
}

export namespace MoveResult {
    export type Changed = Changed.Item[];

    export namespace Changed {
        export interface Item {
            from?: string | undefined;
            to?: string | undefined;
        }
    }
}
