// This file was auto-generated by Fern from our API Definition.

import type * as AgentlefsApi from "../index.js";

export interface RevokeResult extends AgentlefsApi.Grant {
    revoked?: boolean | undefined;
}
