// This file was auto-generated by Fern from our API Definition.

import type * as ContexthubApi from "../index.js";

export interface RevokeResult extends ContexthubApi.Grant {
    revoked?: boolean | undefined;
}
