// This file was auto-generated by Fern from our API Definition.

export const SearchRequestMode = {
    All: "all",
    Auto: "auto",
    Titles: "titles",
    Labels: "labels",
    Text: "text",
    Meaning: "meaning",
} as const;
export type SearchRequestMode = (typeof SearchRequestMode)[keyof typeof SearchRequestMode];
