// This file was auto-generated by Fern from our API Definition.

import type * as ContexthubApi from "../index.js";

export interface SearchResults {
    query?: string | undefined;
    mode_requested?: string | undefined;
    /** Which strategies actually ran. */
    mode_effective?: string[] | undefined;
    /**
     * True when semantic search could not run because this
     * deployment has no vector index. Check it: a lexical-only
     * result to a semantic question can look complete and not be.
     */
    degraded?: boolean | undefined;
    /**
     * True when the sweep cap was reached, so results are partial.
     * A short result must never look complete.
     */
    truncated?: boolean | undefined;
    hits?: ContexthubApi.SearchHit[] | undefined;
}
