// This file was auto-generated by Fern from our API Definition.

export interface SearchHit {
    /** The whole path from the workspace root. */
    location?: string | undefined;
    title?: (string | null) | undefined;
    type?: string | undefined;
    labels?: string[] | undefined;
    is_asset?: boolean | undefined;
    /** The strongest access you hold here. Every hit is at least readable. */
    access?: string | undefined;
    snippet?: (string | null) | undefined;
    /** 1-indexed line number, text mode only. */
    line?: (number | null) | undefined;
    /** Cosine similarity, meaning mode only. */
    score?: (number | null) | undefined;
}
