// This file was auto-generated by Fern from our API Definition.

export interface WriteResult {
    /** The whole path from the workspace root. */
    location?: string | undefined;
    commit?: (string | null) | undefined;
    /** Present and true when this was an idempotent replay. */
    replayed?: boolean | undefined;
}
