// This file was auto-generated by Fern from our API Definition.

export const ListGrantsRequestScopeType = {
    Document: "document",
    Folder: "folder",
    Tenant: "tenant",
} as const;
export type ListGrantsRequestScopeType = (typeof ListGrantsRequestScopeType)[keyof typeof ListGrantsRequestScopeType];
