// This file was auto-generated by Fern from our API Definition.

export const RevokeGrantRequestSubjectType = {
    User: "user",
    Group: "group",
} as const;
export type RevokeGrantRequestSubjectType =
    (typeof RevokeGrantRequestSubjectType)[keyof typeof RevokeGrantRequestSubjectType];
