// This file was auto-generated by Fern from our API Definition.

export const RevokeGrantRequestRole = {
    Owner: "owner",
    Writer: "writer",
    Reader: "reader",
} as const;
export type RevokeGrantRequestRole = (typeof RevokeGrantRequestRole)[keyof typeof RevokeGrantRequestRole];
