// This file was auto-generated by Fern from our API Definition.

export const RevokeGrantRequestScopeType = {
    Document: "document",
    Folder: "folder",
    Tenant: "tenant",
} as const;
export type RevokeGrantRequestScopeType =
    (typeof RevokeGrantRequestScopeType)[keyof typeof RevokeGrantRequestScopeType];
