// This file was auto-generated by Fern from our API Definition.

import type * as ContexthubApi from "../../../../index.js";

/**
 * @example
 *     {
 *         subject_type: "user",
 *         subject_id: "subject_id",
 *         role: "owner",
 *         scope_type: "document",
 *         scope_id: "scope_id"
 *     }
 */
export interface RevokeGrantRequest {
    subject_type: ContexthubApi.RevokeGrantRequestSubjectType;
    subject_id: string;
    role: ContexthubApi.RevokeGrantRequestRole;
    /**
     * Which kind of thing `scope_id` names. Required and never inferred: a document
     * and a directory can share a path and are different scopes with different
     * owners.
     */
    scope_type: ContexthubApi.RevokeGrantRequestScopeType;
    /** The scope, slash-joined. `handbook`, `handbook/policies`, `handbook/leave.md`. */
    scope_id: string;
}
