// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as ContexthubApi from "../index.js";

export class UnauthorizedError extends errors.ContexthubApiError {
    public declare readonly body: ContexthubApi.Error_;

    constructor(body: ContexthubApi.Error_, rawResponse?: core.RawResponse) {
        super({
            message: "UnauthorizedError",
            statusCode: 401,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "UnauthorizedError";
    }
}
