// This file was auto-generated by Fern from our API Definition.

import type * as ContexthubApi from "../../index.js";

/**
 * @example
 *     {
 *         q: "q"
 *     }
 */
export interface SearchRequest {
    q: string;
    /**
     * `auto` (default) picks a strategy from the query shape. `all` runs
     * several and merges. `titles`, `labels`, `text`, and `meaning` force one.
     */
    mode?: ContexthubApi.SearchRequestMode;
    /** Restrict to one folder. Omit to sweep everything you reach. */
    folder?: string;
    /** Maximum items to return. Clamped to the server maximum (50). */
    limit?: number;
}
