// This file was auto-generated by Fern from our API Definition.

export const AgentlefsApiEnvironment = {
    Production: "https://agentlefs.com",
} as const;

export type AgentlefsApiEnvironment = typeof AgentlefsApiEnvironment.Production;
