// This file was auto-generated by Fern from our API Definition.

export const ContexthubApiEnvironment = {
    Production: "https://trycontexthub.com",
} as const;

export type ContexthubApiEnvironment = typeof ContexthubApiEnvironment.Production;
