// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         location: "sales/eu"
 *     }
 */
export interface ListDocumentsRequest {
    /**
     * Where to act, as ONE whole path from the workspace root — `sales` for a
     * top-level folder, `sales/eu` for a directory inside one. There is no separate
     * `folder` parameter: a location says where something is in a single string, so
     * a caller never has to decide where the folder stops and the path begins.
     */
    location: string;
    /** Restrict to one document type. */
    type?: string;
    /**
     * Restrict to documents carrying this label. Labels drive discovery only;
     * they carry no access authority whatsoever.
     */
    label?: string;
    /** Maximum items to return. Clamped to the server maximum (50). */
    limit?: number;
    /**
     * The `next_cursor` from a previous response. Cursors are signed and bound to
     * your key and to the exact query that produced them; a modified or borrowed
     * cursor is rejected with `400` rather than being reinterpreted.
     */
    cursor?: string;
}
