// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         folder: "folder"
 *     }
 */
export interface ListDocumentsRequest {
    /** The folder the document lives in. */
    folder: string;
    /** Restrict to documents under this path prefix within the folder. */
    path?: string;
    /** Restrict to one document type. */
    type?: string;
    /**
     * Restrict to documents carrying this label. Labels drive discovery only;
     * they carry no access authority whatsoever.
     */
    label?: string;
    /** Maximum items to return. Clamped to the server maximum (50). */
    limit?: number;
    /**
     * The `next_cursor` from a previous response. Cursors are signed and bound to
     * your key and to the exact query that produced them; a modified or borrowed
     * cursor is rejected with `400` rather than being reinterpreted.
     */
    cursor?: string;
}
