// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         from_folder: "drafts",
 *         from: "q3-plan.md",
 *         to_folder: "handbook",
 *         to: "planning/q3-plan.md"
 *     }
 */
export interface MoveDocumentRequest {
    /**
     * A unique string per logical operation, at most 255 printable ASCII
     * characters. Retrying with the same key and body returns the first outcome
     * instead of acting twice. Idempotency keys are scoped to your key's principal
     * and expire after 24 hours; that expiry is on the replay key, not on your API
     * key.
     */
    "Idempotency-Key": string;
    from_folder: string;
    from: string;
    to_folder: string;
    to: string;
    /** Set true to proceed with a move that widens access. */
    acknowledge_access_change?: boolean;
}
