// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         folder: "handbook",
 *         from: "onboarding/day-one.md",
 *         name: "day-1.md"
 *     }
 */
export interface RenameDocumentRequest {
    /**
     * A unique string per logical operation, at most 255 printable ASCII
     * characters. Retrying with the same key and body returns the first outcome
     * instead of acting twice. Idempotency keys are scoped to your key's principal
     * and expire after 24 hours; that expiry is on the replay key, not on your API
     * key.
     */
    "Idempotency-Key": string;
    folder: string;
    /** Current path of the document or directory. */
    from: string;
    /** New name. No slashes. */
    name: string;
    /**
     * Set true to proceed with a rename that widens access, after the
     * reported change has been reviewed.
     */
    acknowledge_access_change?: boolean;
}
