// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         path: "onboarding/day-one.md",
 *         folder: "folder"
 *     }
 */
export interface RetrieveDocumentRequest {
    /**
     * The document path within the folder, URL-encoded once. An encoded slash
     * (`%2F`) is rejected: use the literal path separator so the path means the
     * same thing to us as it does to you.
     */
    path: string;
    /** The folder the document lives in. */
    folder: string;
    /** Byte offset, for paging through a document larger than the read cap. */
    offset?: number;
}
