// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListFoldersRequest {
    /** Folder id to list inside, for example `handbook` or `handbook/vendor`. */
    parent?: string;
    /** Maximum items to return. Clamped to the server maximum (50). */
    limit?: number;
    /**
     * The `next_cursor` from a previous response. Cursors are signed and bound to
     * your key and to the exact query that produced them; a modified or borrowed
     * cursor is rejected with `400` rather than being reinterpreted.
     */
    cursor?: string;
}
